name: Self-hosted Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Run docker-compose in TS-EQ-INFRA
        run: |
          cd ~/TS-EQ-INFRA
          docker compose up -d
