name: Self-hosted Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Change dir, chmod and run install.sh
        run: |
          cd ~/test-swarm-setup/TS-EQ-INFRA
          chmod +x ./install.sh
          sudo ./install.sh
      - name: Wait for db-migrator replicas to become 0/1
        run: |
          echo "Waiting for db-migrator replicas to become 0/1..."
          timeout=180  # max wait time in seconds (3 minutes)
          interval=5    # check every 5 seconds

          while [ $timeout -gt 0 ]; do
            replicas=$(docker service ls --filter name=ts-wms_db-migrator --format '{{.Replicas}}')
            
            if [ "$replicas" = "0/1" ]; then
              echo "db-migrator has completed and exited."
              exit 0
            fi

            echo "Still waiting... current replicas: $replicas"
            sleep $interval
            timeout=$((timeout - interval))
          done

          echo "Timeout: db-migrator did not exit within expected time."
          exit 1

  test:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-
      - name: Install Playwright Browsers (if not cached)
        run: |
          if [ ! -d ~/.cache/ms-playwright ]; then
            npx playwright install --with-deps
          fi
      - name: Run Playwright tests
        run: npx playwright test --trace on

  cleanup:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Remove ts-wms docker stack
        run: |
          cd ~/test-swarm-setup/TS-EQ-INFRA
          docker stack rm ts-wms
      - name: Remove secrets created for stack setup
        run: |
          docker secret rm $(docker secret ls -q) 2>/dev/null || true
      - name: Remove volumes created for stack setup
        run: |
          docker volume ls -q --filter name=^ts-wms | xargs -I {} docker volume rm {} 2>/dev/null || true

